language: r
r:
 - release
 - devel
sudo: false

r_check_args: --as-cran --run-donttest

warnings_are_errors: true

cache: packages

bioc_packages:
 - graph
 - Rgraphviz

r_github_packages:
 - r-lib/covr
 - mangothecat/visualTest

after_success:
  - Rscript -e 'library("covr"); codecov(type="all")'

