language: r
sudo: required

r_check_args: --as-cran --run-donttest

warnings_are_errors: true

r_binary_packages:
 - numDeriv
 - mets
 - igraph
 - lme4
 - fields
 - foreach
 - rgl
 - plyr
 - nloptr
 - minqa
 - maps
 - geepack

github_packages:
 - hadley/testthat
 - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

before_install:
  - sudo apt-get install -y r-bioc-rgraphviz r-bioc-graph
#bioc_packages:
# - graph
