language: r

r:
 - release
#- devel

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --ignore-vignettes --no-manual --timings --run-donttest --no-stop-on-test-error

warnings_are_errors: true

cache: packages

addons:
  apt:
    update: true
    packages:
      - libglu1-mesa-dev
      - mesa-common-dev

r_packages:
  - covr
  - png
  - pkgdown

bioc_packages:
  - graph
  - Rgraphviz

r_github_packages:
  - mangothecat/visualTest

after_success:
  - Rscript -e 'covr::codecov(type=c("tests", "examples"))'

notifications:
  slack:
    secure: E04dZH66z76WoTRUsSNvhk5gCRIGttal/oICu5XGrQkklKhDRK3y7gc6Z94rzDzd2LVyYBe/xD0//FrOStV/rBIYPmJ5gC0ak+14lr1oX6X8dIPhM00fYJbT1GozBKPu5m61lntyYHBltI9emsNJ8TYBznhpM4epNdK+xUU9DLtr3Efcwq+MIvSCP3PvMbYIHnFb8RBz+aNprEc/t5bgRZpfaAtCWJUd9LNz3Y2SlThOpIrgrNd3IfGj0XNkPBWydxebzPf9XBk9wI0xcxdP+RWjixFolwTNGx1kgmnze5NkZUwpM3xm8epkJ+slBNnz4LXVIYwgqJCDO5zrdSlYbfhKvizA56mTxDm45PlZuGFDiGcTYfDP/buKDjEgx2J6Hh9Pr1f+5P37BTRCkN+JQGBbM+OEGndgsDig63GhXXnacIsDZjQnTf6irWJGCuiih2cNkmnx+KTtpVANqfaRT5juEv6XZPlOKE8Lv/jvGHenUWx0pfltH7zVuw1eO66C1wqOXp4qL1fXMuKt7ZFmf6E/Mp0f1g07TpNli/j7Fz4ULnP0ILex63CuHEIKpO15FOGZGO9959qIztB9UGPaotfEnk0azfaI6sq1dTcHizlS/ie9oYViuQ+m7jA2dKQT59t7trXUAe1qOsv+tcHZ1LuLUYC+srSMcBn9gpmu7VA=

before_deploy:
  - travis_wait 30 Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master
    condition: "$TRAVIS_R_VERSION_STRING = release"
