language: r
sudo: required
r_check_args: --as-cran --run-donttest
r_binary_packages:
 - numDeriv
 - mets
 - igraph
 - lme4
 - fields
 - foreach
 - rgl
 - plyr
 - nloptr
 - minqa
 - maps
 - geepack
 - Rgraphviz

bioc_packages:
 - graph

github_packages:
 - hadley/testthat