language: r
r:
 - release
 - devel
sudo: false
r_check_args: --as-cran --run-donttest
warnings_are_errors: true
cache: packages

r_packages:
 - numDeriv
 - mets
 - covr
 - testthat
 - optimx
 - data.table
 - igraph
 - visNetwork
 - Matrix
 - KernSmooth
 - lme4
 - geepack
 - gof
 - foreach
 - quantreg
 - rgl
 - fields
 - survival
 - ascii
 - zoo

bioc_packages:
 - graph
 - Rgraphviz

r_github_packages:
# - jimhester/covr
 - mangothecat/visualTest

after_success:
  - Rscript -e 'library("covr"); codecov(type="test")'

